version: '3.8'

services:
  web:
    image: mygraph-builder:1.0.0
    command: npm run start
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - SEED_DB=yes
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    ports:
       - 5432:5432
    volumes:
      - mygraph_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  mygraph_data:

